services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    restart: unless-stopped
    networks:
      - proxy-network
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BASE_URL=http://185.229.220.75:3001

networks:
  proxy-network:
    external: true
    name: proxy-network
